# Site settings
title: Connect 4 Game
author:
  name: Joseph Thomas
  email: 1andonlyjopa45@gmail.com
description: "All about my Connect 4 Game and how to install it."
github_username: JoeT00

# Build settings
remote_theme: jekyll/minima
